# Clawdbot configuration for mattermost-plugin-boards
# Pre-commit checks run locally before pushing to avoid CI failures

pre_commit:
  # Go formatting (auto-fix)
  - gofmt -w server/

  # Go linting
  - make server-lint

  # Go unit tests — SKIPPED: sqlite3 driver requires CGO which is not available
  # in this environment. Server tests are run by GitHub CI instead.
  # - make server-test

  # Webapp linting
  - cd webapp && npm run lint

  # Webapp type checking
  - cd webapp && npm run check-types

# Timeouts (seconds)
timeouts:
  pre_commit: 600   # 10 min for all checks
  auggie: 900       # 15 min for Auggie work
