version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - durationcheck
    - err113
    - errorlint
    - exhaustive
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    govet:
      disable:
        - fieldalignment
      enable-all: true
    lll:
      line-length: 150
    misspell:
      locale: US
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - unused
        path: server/manifest.go
      - linters:
          - unused
        path: server/configuration.go
      - linters:
          - bodyclose
        path: _test\.go
      # QF1008 - ignoring for now and must be revisited after bumping lint version.
      - linters:
          - staticcheck
        text: QF1008
        path: app/category_boards.go
      - linters:
          - staticcheck
        text: QF1008
        path: plugin.go
      - linters:
          - staticcheck
        text: QF1008
        path: services/metrics/service.go
      - linters:
          - staticcheck
        text: QF1008
        path: web/webserver.go
      # QF1003: this file is using boardTypes undefined in the models - must be revisited after bumping lint version.
      - linters:
          - staticcheck
        text: QF1003
        path: store/sqlstore/data_migrations.go
    paths:
      - product/boards_product.go
      - services/store/sqlstore/migrations
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        # todo: update to the correct module name after bumping lint version.
        - github.com/mattermost/mattermost-starter-template
  exclusions:
    generated: lax
    paths:
      - product/boards_product.go
      - services/store/sqlstore/migrations
      - third_party$
      - builtin$
      - examples$
