run:
  timeout: 5m
  modules-download-mode: readonly
  skip-files:
    - product/boards_product.go
    - services/store/sqlstore/migrations

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/mattermost/mattermost-starter-template
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
  misspell:
    locale: US
  lll:
    line-length: 150
  revive:
    enableAllRules: true
    rules:
      - name: exported
        disabled: true

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - ineffassign
    - unparam
    - govet
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - gosec
    - makezero
    - staticcheck
    - prealloc
    - asciicheck
    - dogsled
    - gocritic
    - godot
    - err113
    - goheader
    - revive
    - nakedret
    - gomodguard
    - goprintffuncname
    - gosimple
    - misspell
    - nolintlint
    - typecheck
    - unconvert
    - unused
    - whitespace
    - gocyclo

issues:
  exclude-rules:
    - path: server/manifest.go
      linters:
        - unused
    - path: server/configuration.go
      linters:
        - unused
    - path: _test\.go
      linters:
        - bodyclose
        - scopelint # https://github.com/kyoh86/scopelint/issues/4
