version: 2

run:
  timeout: 5m

linters-settings:
  govet:
    enable:
      - shadow
    disable:
      - fieldalignment

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    
issues:
  exclude-files:
    - product/boards_product.go
    - services/store/sqlstore/migrations
  exclude-rules:
    - path: server/manifest.go
      linters:
        - unused
    - path: server/configuration.go  
      linters:
        - unused
    - path: _test\.go
      linters:
        - bodyclose
