version: '2.4'
services:
  postgres:
    image: "postgres:10"
    restart: always
    environment:
      POSTGRES_USER: mmuser
      POSTGRES_PASSWORD: mostest
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 3
    tmpfs: /var/lib/postgresql/data
    ports:
      - 44447:5432

  start_dependencies:
    image: mattermost/mattermost-wait-for-dep:latest
    depends_on:
      - postgres
    command: postgres:5432

