name: Dev-Release

on:
  push:
    branches: [ main, release-** ]
  pull_request:
    branches: [ main, release-** ]
  workflow_dispatch:

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
 EXCLUDE_ENTERPRISE: true

jobs:

  plugin:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        path: "focalboard"

    - name: Replace token 1 server
      run: sed -i -e "s,placeholder_rudder_dataplane_url,${{ secrets.RUDDER_DATAPLANE_URL }},g" ${{ github.workspace }}/focalboard/server/services/telemetry/telemetry.go

    - name: Replace token 1 webapp
      run: sed -i -e "s,placeholder_rudder_dataplane_url,${{ secrets.RUDDER_DATAPLANE_URL }},g" ${{ github.workspace }}/focalboard/webapp/src/index.tsx

    - name: Replace token 2 server
      run: sed -i -e "s,placeholder_rudder_key,${{ secrets.RUDDER_DEV_KEY }},g" ${{ github.workspace }}/focalboard/server/services/telemetry/telemetry.go

    - name: Replace token 2 webapp
      run: sed -i -e "s,placeholder_rudder_key,${{ secrets.RUDDER_DEV_KEY }},g" ${{ github.workspace }}/focalboard/webapp/src/index.tsx

    - name: npm ci
      run: cd focalboard/webapp; npm ci --no-optional

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 20.11.0

    - name: Build webapp
      run: cd focalboard; make webapp

    - name: npm ci plugin dependencies
      run: cd focalboard/webapp; npm ci --no-optional

    - name: Build plugin
      run: cd focalboard; make dist
      env:
        BUILD_NUMBER: ${{ github.run_id }}

    - name: Rename plugin file
      run: cd focalboard/dist; mv focalboard-*.tar.gz mattermost-plugin-focalboard.tar.gz

    - name: Upload plugin artifact
      uses: actions/upload-artifact@v3
      with:
        name: mattermost-plugin-focalboard.tar.gz
        path: ${{ github.workspace }}/focalboard/dist/mattermost-plugin-focalboard.tar.gz
